version: '3.1'

services:

#  mongo:
#    container_name: mongo-ex
#    image: mongo:latest
#    network_mode: host
#    ports:
#      - "27017:27017"
#
#  pyapp:
#    container_name: python-app
#    image: python-ex-img:latest
#    network_mode: host
#    ports:
#      - "5000:5000"

  web:
    container_name: efk-httpd
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    container_name: efk-fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: efk-elastic
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    container_name: efk-kibana
    image: kibana
    links:
      - "elasticsearch"
    ports:
    - "5601:5601"


